services:
  bot:
    container_name: database_service
    hostname: database_service
    build: .
    restart: always
    ports:
      - 44044:44044
    command: [
        "/app/service",
        "--config=local.yaml"
    ]